version: '0.1.3-beta-{build}'

platform: Any CPU
configuration: Release
os: Visual Studio 2017

before_build:
  - dotnet restore  
  - dotnet restore .\NetCoreTeamCity.Tests

build:
  parallel: true            
  project: NetCoreTeamCity.sln
  
after_build:
  - dotnet pack ".\NetCoreTeamCity\NetCoreTeamCity.csproj" -c %CONFIGURATION% -o ..\artifacts
test_script:
  - dotnet test ".\NetCoreTeamCity.Tests\NetCoreTeamCity.Tests.csproj" -c %CONFIGURATION% --logger:trx;LogFileName=tests-results01.xml
  - ps: .\build\uploadtests.ps1 ".\NetCoreTeamCity.Tests\TestResults\tests-results01.xml"
artifacts:
  - path: artifacts\**\*.*
cache:
  - '%USERPROFILE%\.nuget\packages'
deploy:
  provider: NuGet
  api_key:
    secure: eAmrqTsMvAzBJPXcGNZZGrH7lHqaqqd5Fcql/7ELY2GbvPYx03nAMm1kCvcoL2Rr
  skip_symbols: false
  artifact: /.*\.nupkg/
